In [1]:
pwd

'C:\\Users\\zcode\\Desktop\\py\\데이터분석 및 시각화\\01판다스'

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
plt.rcParams['font.family'] ='Malgun Gothic'
plt.rcParams['axes.unicode_minus'] =False
df = pd.read_csv('./data/cctv_in_seoul.csv')
print(df.shape)
df.head()

(25, 6)

   기관명    소계  2013년도 이전  2014년  2015년  2016년
0  강남구  3238       1292    430    584    932
1  강동구  1010        379     99    155    377
2  강북구   831        369    120    138    204
3  강서구   911        388    258    184     81
4  관악구  2109        846    260    390    613

In [3]:
df['지역']='서울'

In [4]:
df

     기관명    소계  2013년도 이전  2014년  2015년  2016년  지역
0    강남구  3238       1292    430    584    932  서울
1    강동구  1010        379     99    155    377  서울
2    강북구   831        369    120    138    204  서울
3    강서구   911        388    258    184     81  서울
4    관악구  2109        846    260    390    613  서울
5    광진구   878        573     78     53    174  서울
6    구로구  1884       1142    173    246    323  서울
7    금천구  1348        674     51    269    354  서울
8    노원구  1566        542     57    451    516  서울
9    도봉구   825        238    159     42    386  서울
10  동대문구  1870       1070     23    198    579  서울
11   동작구  1302        544    341    103    314  서울
12   마포구   980        314    118    169    379  서울
13  서대문구  1254        844     50     68    292  서울
14   서초구  2297       1406    157    336    398  서울
15   성동구  1327        730     91    241    265  서울
16   성북구  1651       1009     78    360    204  서울
17   송파구  1081        529     21     68    463  서울
18   양천구  2482       1843    142     30    467  서울
19  영등포구  1277        495    214    195    373  서울
20   용산구  2096       1368    218    112    398  서울
21   은평구  2108       1138    224    278    468  서울
22   종로구  1619        464    314    211    630  서울
23    중구  1023        413    190     72    348  서울
24   중랑구   916        509    121    177    109  서울

In [5]:
df['2016년 증감']=df['2016년']-df['2015년']

In [6]:
df

     기관명    소계  2013년도 이전  2014년  2015년  2016년  지역  2016년 증감
0    강남구  3238       1292    430    584    932  서울       348
1    강동구  1010        379     99    155    377  서울       222
2    강북구   831        369    120    138    204  서울        66
3    강서구   911        388    258    184     81  서울      -103
4    관악구  2109        846    260    390    613  서울       223
5    광진구   878        573     78     53    174  서울       121
6    구로구  1884       1142    173    246    323  서울        77
7    금천구  1348        674     51    269    354  서울        85
8    노원구  1566        542     57    451    516  서울        65
9    도봉구   825        238    159     42    386  서울       344
10  동대문구  1870       1070     23    198    579  서울       381
11   동작구  1302        544    341    103    314  서울       211
12   마포구   980        314    118    169    379  서울       210
13  서대문구  1254        844     50     68    292  서울       224
14   서초구  2297       1406    157    336    398  서울        62
15   성동구  1327        730     91    241    265  서울        24
16   성북구  1651       1009     78    360    204  서울      -156
17   송파구  1081        529     21     68    463  서울       395
18   양천구  2482       1843    142     30    467  서울       437
19  영등포구  1277        495    214    195    373  서울       178
20   용산구  2096       1368    218    112    398  서울       286
21   은평구  2108       1138    224    278    468  서울       190
22   종로구  1619        464    314    211    630  서울       419
23    중구  1023        413    190     72    348  서울       276
24   중랑구   916        509    121    177    109  서울       -68

In [7]:
res = []
for i in df['2016년 증감']:
    if i >=0 :
        res.append('증가')
    else :
        res.append('감소')
df['기타'] = res
df.head()

   기관명    소계  2013년도 이전  2014년  2015년  2016년  지역  2016년 증감  기타
0  강남구  3238       1292    430    584    932  서울       348  증가
1  강동구  1010        379     99    155    377  서울       222  증가
2  강북구   831        369    120    138    204  서울        66  증가
3  강서구   911        388    258    184     81  서울      -103  감소
4  관악구  2109        846    260    390    613  서울       223  증가

In [8]:
res = ['증가' if i >= 0 else '감소' for i in df['2016년 증감']]
df['비고1'] = res
df.head()

   기관명    소계  2013년도 이전  2014년  2015년  2016년  지역  2016년 증감  기타 비고1
0  강남구  3238       1292    430    584    932  서울       348  증가  증가
1  강동구  1010        379     99    155    377  서울       222  증가  증가
2  강북구   831        369    120    138    204  서울        66  증가  증가
3  강서구   911        388    258    184     81  서울      -103  감소  감소
4  관악구  2109        846    260    390    613  서울       223  증가  증가

In [9]:
df['2016년'].describe()

count     25.000000
mean     385.880000
std      182.479981
min       81.000000
25%      292.000000
50%      377.000000
75%      467.000000
max      932.000000
Name: 2016년, dtype: float64

In [10]:
res = []
for i in df['2016년']:
    if i <= 292:
        tmp = '하'
    elif i <= 467:
        tmp = '중'
    else :
        tmp = '상'
    res.append(tmp)
df['구분']=res
df

     기관명    소계  2013년도 이전  2014년  2015년  2016년  지역  2016년 증감  기타 비고1 구분
0    강남구  3238       1292    430    584    932  서울       348  증가  증가  상
1    강동구  1010        379     99    155    377  서울       222  증가  증가  중
2    강북구   831        369    120    138    204  서울        66  증가  증가  하
3    강서구   911        388    258    184     81  서울      -103  감소  감소  하
4    관악구  2109        846    260    390    613  서울       223  증가  증가  상
5    광진구   878        573     78     53    174  서울       121  증가  증가  하
6    구로구  1884       1142    173    246    323  서울        77  증가  증가  중
7    금천구  1348        674     51    269    354  서울        85  증가  증가  중
8    노원구  1566        542     57    451    516  서울        65  증가  증가  상
9    도봉구   825        238    159     42    386  서울       344  증가  증가  중
10  동대문구  1870       1070     23    198    579  서울       381  증가  증가  상
11   동작구  1302        544    341    103    314  서울       211  증가  증가  중
12   마포구   980        314    118    169    379  서울       210  증가  증가  중
13  서대문구  1254        844     50     68    292  서울       224  증가  증가  하
14   서초구  2297       1406    157    336    398  서울        62  증가  증가  중
15   성동구  1327        730     91    241    265  서울        24  증가  증가  하
16   성북구  1651       1009     78    360    204  서울      -156  감소  감소  하
17   송파구  1081        529     21     68    463  서울       395  증가  증가  중
18   양천구  2482       1843    142     30    467  서울       437  증가  증가  중
19  영등포구  1277        495    214    195    373  서울       178  증가  증가  중
20   용산구  2096       1368    218    112    398  서울       286  증가  증가  중
21   은평구  2108       1138    224    278    468  서울       190  증가  증가  상
22   종로구  1619        464    314    211    630  서울       419  증가  증가  상
23    중구  1023        413    190     72    348  서울       276  증가  증가  중
24   중랑구   916        509    121    177    109  서울       -68  감소  감소  하

In [11]:
df['구분'].value_counts()

구분
중    12
하     7
상     6
Name: count, dtype: int64

In [12]:
a = [1,2,3,4,5,6,7,8,9]
pd.cut(a,bins=3, labels=['하','중','상'])

['하', '하', '하', '중', '중', '중', '상', '상', '상']
Categories (3, object): ['하' < '중' < '상']

In [13]:
a = [1,8,3,4,5,6,7,8,9]
pd.cut(a,bins=3, labels=['하','중','상'])

['하', '상', '하', '중', '중', '중', '상', '상', '상']
Categories (3, object): ['하' < '중' < '상']

In [14]:
a = [1,8,3,4,5,6,7,8,9,100]
pd.cut(a,bins=3, labels=['하','중','상'])

['하', '하', '하', '하', '하', '하', '하', '하', '하', '상']
Categories (3, object): ['하' < '중' < '상']

In [15]:
a = [1,2,3,4,5,6,7,8,9]
pd.qcut(a, q=3, labels=['하','중','상'])

['하', '하', '하', '중', '중', '중', '상', '상', '상']
Categories (3, object): ['하' < '중' < '상']

In [16]:
a = [1,2,3,4,5,6,7,8,9,100]
pd.qcut(a, q=3, labels=['하','중','상'])

['하', '하', '하', '중', '중', '중', '상', '상', '상', '상']
Categories (3, object): ['하' < '중' < '상']

In [17]:
a = [1,8,3,4,5,6,7,8,9,100]
pd.qcut(a, q=3, labels=['하','중','상'])

['하', '상', '하', '하', '중', '중', '중', '상', '상', '상']
Categories (3, object): ['하' < '중' < '상']

In [18]:
점수 = [90, 89, 79, 69, 81, 80, 100] # A, B, C, D, B, B
pd.cut(점수, bins=[0,60,70,80,90,101], labels=['F','D','C','B','A'] ,right=False)

['A', 'B', 'C', 'D', 'B', 'B', 'A']
Categories (5, object): ['F' < 'D' < 'C' < 'B' < 'A']

In [19]:
df['구분1'] = pd.cut(df['2016년'], bins=3, labels=['하','중','상'])
df

     기관명    소계  2013년도 이전  2014년  2015년  2016년  지역  2016년 증감  기타 비고1 구분 구분1
0    강남구  3238       1292    430    584    932  서울       348  증가  증가  상   상
1    강동구  1010        379     99    155    377  서울       222  증가  증가  중   중
2    강북구   831        369    120    138    204  서울        66  증가  증가  하   하
3    강서구   911        388    258    184     81  서울      -103  감소  감소  하   하
4    관악구  2109        846    260    390    613  서울       223  증가  증가  상   중
5    광진구   878        573     78     53    174  서울       121  증가  증가  하   하
6    구로구  1884       1142    173    246    323  서울        77  증가  증가  중   하
7    금천구  1348        674     51    269    354  서울        85  증가  증가  중   하
8    노원구  1566        542     57    451    516  서울        65  증가  증가  상   중
9    도봉구   825        238    159     42    386  서울       344  증가  증가  중   중
10  동대문구  1870       1070     23    198    579  서울       381  증가  증가  상   중
11   동작구  1302        544    341    103    314  서울       211  증가  증가  중   하
12   마포구   980        314    118    169    379  서울       210  증가  증가  중   중
13  서대문구  1254        844     50     68    292  서울       224  증가  증가  하   하
14   서초구  2297       1406    157    336    398  서울        62  증가  증가  중   중
15   성동구  1327        730     91    241    265  서울        24  증가  증가  하   하
16   성북구  1651       1009     78    360    204  서울      -156  감소  감소  하   하
17   송파구  1081        529     21     68    463  서울       395  증가  증가  중   중
18   양천구  2482       1843    142     30    467  서울       437  증가  증가  중   중
19  영등포구  1277        495    214    195    373  서울       178  증가  증가  중   중
20   용산구  2096       1368    218    112    398  서울       286  증가  증가  중   중
21   은평구  2108       1138    224    278    468  서울       190  증가  증가  상   중
22   종로구  1619        464    314    211    630  서울       419  증가  증가  상   중
23    중구  1023        413    190     72    348  서울       276  증가  증가  중   하
24   중랑구   916        509    121    177    109  서울       -68  감소  감소  하   하

In [20]:
d

NameError: name 'd' is not defined

In [ ]:
df['구분1'].value_counts()

In [ ]:
df['2016년'].describe()

In [ ]:
df['2016년'].plot(kind='box')

In [ ]:
df[df['2016년']>800]

In [ ]:
df.head()

In [ ]:
df.columns

In [ ]:
cols = ['2013년도 이전', '2014년', '2015년', '2016년']
df[cols].plot(kind='box')

In [ ]:
df.head()

In [21]:
df

     기관명    소계  2013년도 이전  2014년  2015년  2016년  지역  2016년 증감  기타 비고1 구분 구분1
0    강남구  3238       1292    430    584    932  서울       348  증가  증가  상   상
1    강동구  1010        379     99    155    377  서울       222  증가  증가  중   중
2    강북구   831        369    120    138    204  서울        66  증가  증가  하   하
3    강서구   911        388    258    184     81  서울      -103  감소  감소  하   하
4    관악구  2109        846    260    390    613  서울       223  증가  증가  상   중
5    광진구   878        573     78     53    174  서울       121  증가  증가  하   하
6    구로구  1884       1142    173    246    323  서울        77  증가  증가  중   하
7    금천구  1348        674     51    269    354  서울        85  증가  증가  중   하
8    노원구  1566        542     57    451    516  서울        65  증가  증가  상   중
9    도봉구   825        238    159     42    386  서울       344  증가  증가  중   중
10  동대문구  1870       1070     23    198    579  서울       381  증가  증가  상   중
11   동작구  1302        544    341    103    314  서울       211  증가  증가  중   하
12   마포구   980        314    118    169    379  서울       210  증가  증가  중   중
13  서대문구  1254        844     50     68    292  서울       224  증가  증가  하   하
14   서초구  2297       1406    157    336    398  서울        62  증가  증가  중   중
15   성동구  1327        730     91    241    265  서울        24  증가  증가  하   하
16   성북구  1651       1009     78    360    204  서울      -156  감소  감소  하   하
17   송파구  1081        529     21     68    463  서울       395  증가  증가  중   중
18   양천구  2482       1843    142     30    467  서울       437  증가  증가  중   중
19  영등포구  1277        495    214    195    373  서울       178  증가  증가  중   중
20   용산구  2096       1368    218    112    398  서울       286  증가  증가  중   중
21   은평구  2108       1138    224    278    468  서울       190  증가  증가  상   중
22   종로구  1619        464    314    211    630  서울       419  증가  증가  상   중
23    중구  1023        413    190     72    348  서울       276  증가  증가  중   하
24   중랑구   916        509    121    177    109  서울       -68  감소  감소  하   하

In [22]:
del df['지역']

In [28]:
df = df.drop(['소계','기타'],axis=1)

In [29]:
df

     기관명  2013년도 이전  2014년  2015년  2016년  2016년 증감 비고1 구분 구분1
0    강남구       1292    430    584    932       348  증가  상   상
1    강동구        379     99    155    377       222  증가  중   중
2    강북구        369    120    138    204        66  증가  하   하
3    강서구        388    258    184     81      -103  감소  하   하
4    관악구        846    260    390    613       223  증가  상   중
5    광진구        573     78     53    174       121  증가  하   하
6    구로구       1142    173    246    323        77  증가  중   하
7    금천구        674     51    269    354        85  증가  중   하
8    노원구        542     57    451    516        65  증가  상   중
9    도봉구        238    159     42    386       344  증가  중   중
10  동대문구       1070     23    198    579       381  증가  상   중
11   동작구        544    341    103    314       211  증가  중   하
12   마포구        314    118    169    379       210  증가  중   중
13  서대문구        844     50     68    292       224  증가  하   하
14   서초구       1406    157    336    398        62  증가  중   중
15   성동구        730     91    241    265        24  증가  하   하
16   성북구       1009     78    360    204      -156  감소  하   하
17   송파구        529     21     68    463       395  증가  중   중
18   양천구       1843    142     30    467       437  증가  중   중
19  영등포구        495    214    195    373       178  증가  중   중
20   용산구       1368    218    112    398       286  증가  중   중
21   은평구       1138    224    278    468       190  증가  상   중
22   종로구        464    314    211    630       419  증가  상   중
23    중구        413    190     72    348       276  증가  중   하
24   중랑구        509    121    177    109       -68  감소  하   하

In [32]:
df[['2014년','2015년']].sum()

2014년    3987
2015년    5130
dtype: int64

In [36]:
df[['2014년','2015년']].sum(axis=1)

0     1014
1      254
2      258
3      442
4      650
5      131
6      419
7      320
8      508
9      201
10     221
11     444
12     287
13     118
14     493
15     332
16     438
17      89
18     172
19     409
20     330
21     502
22     525
23     262
24     298
dtype: int64

In [38]:
df.loc[:,'2014년':'2016년'].max(axis=1)

0     932
1     377
2     204
3     258
4     613
5     174
6     323
7     354
8     516
9     386
10    579
11    341
12    379
13    292
14    398
15    265
16    360
17    463
18    467
19    373
20    398
21    468
22    630
23    348
24    177
dtype: int64

In [39]:
df.loc[:,'2014년':'2016년'].max(axis=0)

2014년    430
2015년    584
2016년    932
dtype: int64