In [4]:
import requests
import pandas as pd

In [5]:
url = 'https://finance.naver.com/sise/sise_quant.naver'
html = requests.get(url)
html

In [7]:
len(pd.read_html(html.text))

C:\Users\go121\AppData\Local\Temp\ipykernel_8368\3773159676.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  len(pd.read_html(html.text))

2

In [8]:
pd.read_html(html.text)[0]

C:\Users\go121\AppData\Local\Temp\ipykernel_8368\2544377297.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_html(html.text)[0]

     0      1          2        3          4       5
0  거래량   매수호가   거래대금(백만)  시가총액(억)    영업이익(억)  PER(배)
1   시가   매도호가      전일거래량  자산총계(억)    영업이익증가율  ROE(%)
2   고가  매수총잔량      외국인비율  부채총계(억)   당기순이익(억)  ROA(%)
3   저가  매도총잔량  상장주식수(천주)   매출액(억)   주당순이익(원)  PBR(배)
4  NaN    NaN        NaN   매출액증가율  보통주배당금(원)  유보율(%)

In [20]:
pd.read_html(html.text)[1]

C:\Users\go121\AppData\Local\Temp\ipykernel_8368\3065910340.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_html(html.text)[1]

,N,종목명,현재가,전일비,등락률,거래량,거래대금,매수호가,매도호가,시가총액,PER,ROE
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,KODEX 200선물인버스2X,2240.0,상승 30,+1.36%,136959788.0,306952.0,2235.0,2240.0,12878.0,NaN,NaN
2,2.0,삼성 인버스 2X WTI원유 선물 ETN,85.0,하락 3,-3.41%,111189387.0,9152.0,84.0,85.0,1272.0,NaN,NaN
3,3.0,KODEX 코스닥150선물인버스,3565.0,보합0,0.00%,28403793.0,101254.0,3560.0,3565.0,3105.0,NaN,NaN
4,4.0,삼성전자,60300.0,하락 700,-1.15%,27027052.0,1629596.0,60300.0,60400.0,3599779.0,14.74,4.15
...,...,...,...,...,...,...,...,...,...,...,...,...
156,99.0,삼일제약,17060.0,상승 900,+5.57%,912457.0,15470.0,17060.0,17070.0,3684.0,-254.63,1.31
157,100.0,한국가스공사,44100.0,하락 250,-0.56%,903084.0,39689.0,44050.0,44100.0,40710.0,-24.30,-7.68
158,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN